// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQVBVQKt-rBGfKPG25qfMJDDalXhjr28',
    appId: '1:561119530449:web:f2f9df481112d9732da4f0',
    messagingSenderId: '561119530449',
    projectId: 'gestime-4d2cb',
    authDomain: 'gestime-4d2cb.firebaseapp.com',
    storageBucket: 'gestime-4d2cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyQReIL8uqXcvdQR8p6VEddiBmQsHZaw',
    appId: '1:561119530449:android:0683fcf2975c2e3f2da4f0',
    messagingSenderId: '561119530449',
    projectId: 'gestime-4d2cb',
    storageBucket: 'gestime-4d2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhU27L6IPxfQZEM_L2-xhInRuHcWxT6A',
    appId: '1:561119530449:ios:6804a1c205e598e32da4f0',
    messagingSenderId: '561119530449',
    projectId: 'gestime-4d2cb',
    storageBucket: 'gestime-4d2cb.appspot.com',
    iosBundleId: 'com.example.gestime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvhU27L6IPxfQZEM_L2-xhInRuHcWxT6A',
    appId: '1:561119530449:ios:6804a1c205e598e32da4f0',
    messagingSenderId: '561119530449',
    projectId: 'gestime-4d2cb',
    storageBucket: 'gestime-4d2cb.appspot.com',
    iosBundleId: 'com.example.gestime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmQVBVQKt-rBGfKPG25qfMJDDalXhjr28',
    appId: '1:561119530449:web:3236c7cee979facb2da4f0',
    messagingSenderId: '561119530449',
    projectId: 'gestime-4d2cb',
    authDomain: 'gestime-4d2cb.firebaseapp.com',
    storageBucket: 'gestime-4d2cb.appspot.com',
  );

}